### ISSUE TITLE
[document] path 수정

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/baemin-17#19]
현재 프로젝트 위키 [Routing과 RESTful API](https://github.com/woowa-techcamp-2021/baemin-17/wiki/Routing%EA%B3%BC-RESTful-API)에 있는 주소를 수정해야 할 것 같습니다.

| 페이지 | 현재 | 제안 |
| --- | --- | --- |
| 가입약관 동의 | /agree | /signup/agree |
| 회원가인 - 휴대폰인증 | signup-phone | /signup/phone |
| 회원가입 - 정보입력 | /signup-detail | /signup/detail |

**Comment by KangyeolLee** [comment]
네 좋은 거 같습니다.

기존 라우팅 주소는 제안사항으로 변경하겠습니다!

**Comment by TsooranKim** [comment]
감사합니당~
