### ISSUE TITLE
[bug] 메인페이지 이미지 인코딩 관련 에러

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/baemin-17#26]
이미지 이름을 한글로 지정했을 때

맥OS 에서는 정상적으로 이미지가 출력되지만

윈도우OS 에서는 이미지 깨짐 현상이 발생합니다.

- 레이아웃 화면

![메인](https://user-images.githubusercontent.com/48883344/124715722-41cf4080-df3e-11eb-9329-a43d37c0afd1.PNG)

- 네트워크 탭

![bug](https://user-images.githubusercontent.com/48883344/124715729-4267d700-df3e-11eb-846d-c6dc2aab63eb.PNG)

서로 다른 운영체제 간 인코딩 방식의 차이로 인한 문제로 생각됩니다.

서버에서 동일한 형식으로 처리할 수 있게 관련 코드를 추가하거나

아니면 단순하게 이미지 이름을 모두 영어로 변경하는 방법이 필요할 것 같습니다.

**Comment by TsooranKim** [comment]
한글 파일명을 영어로 바꿔서 문제를 해결하겠습니다~
