### ISSUE TITLE
[document] 중복 방지를 위한 고정 고유 id 값 설정

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/baemin-17#28]
각 스크린 페이지 및 중복 컴포넌트 헤더에게 부여할 고유 id 값이 필요합니다.

해당 컴포넌트 단위는 전체 애플리케이션에서 고유함을 입증할 수 있고

추후 중복으로 인한 문제를 방지하기 위해 고유 id를 할당하고 관리할 문서화가 필요해 보입니다.

때문에 각 항목의 아이디 값을 다음과 같이 관리할 것을 제안합니다.

| num | `id` | 페이지 | 용도 |
|:---|:---|:---|:---|
|1|`#root`|최상단 `div` 태그|`body` 태그 내의 최상위 루트|
|2|`#header`|페이지 헤더|각 페이지 별 존재하는 헤더 태그|
|3|`#main-page`|첫 화면 메인 페이지|기본 화면 페이지의 최상위|
|4|`#login-page`|로그인 페이지|로그인 페이지의 최상위|
|5|`#agreement-page`|가입약관 안내 페이지|가입약관 페이지의 최상위|
|6|`#signup-phone-page`|회원가입-휴대번호 페이지|회원가입-휴대번호 페이지의 최상위|
|7|`#signup-detail-page`|회원가입-상세정보 페이지|회원가입-상세정보 페이지의 최상위|

**Comment by TsooranKim** [comment]
감사합니다~

**Comment by TsooranKim** [comment]
제안을 하신거니까 감사합니다로 말할께 아니라. 동의합니다~ 로 말해야 할라나요? ㅎㅎㅎ

**Comment by KangyeolLee** [comment]
해당 내용은 Wiki에 기록 하겠습니다.

Wiki에서 참고하시면 되겠습니다 :)
