### ISSUE TITLE
[feature] layout.pug에 head 자리 만들기

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/baemin-17#30]
현제 구조가 layout에 content block만 있는 상태여서 head에 내용을 추가하기 위해서는 layout.pug를 수정해야만 합니다.

그렇기에 상속받은 템플릿에서 head에 추가할 수 있는 block이 필요합니다.

또한 title을 수정할 수 있게도 해야합니다.

**Comment by TsooranKim** [comment]
``` javascript
res.render('/some', { title: 'The Title' });
```

``` pug
title= title
```

타이틀의 경우에는 이미 이런식으로 할 수 있었군요.

**Comment by KangyeolLee** [comment]
네 동의합니다!
