### ISSUE TITLE
[feature] reset.css 추가 필요

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/baemin-17#32]
모든 브라우저에서 동일하게 보이기 위한 reset.css가 필요합니다.

또한 Noto-Sans-KR web font 설정이 필요 합니다.

reset.css를 추가하면 기존의 style이 많이 변형 되겠지만 필요한 작업입니다.

**Comment by KangyeolLee** [comment]
네 좋은 의견인 거 같습니다!

추가하더라도 기존 스타일 변경이 크지 않을 거 같습니다 ~~

`stylesheets` 폴더에 새로 `reset.css` 파일 생성 후

`views/layout.pug`에서 링크 추가하면 될 것 같습니다 😊
