### ISSUE TITLE
[bug] 메인 페이지 로그인 버튼 이동 경로 설정

### ISSUE THREAD

**Issue by KangyeolLee** [woowa-techcamp-2021/baemin-17#40]
메인 페이지 로그인 버튼 클릭 시 로그인 페이지로 이동해야 하지만

현재 해시경로(`#`)가 지정되어 있습니다.

해당 경로를 `/login` 으로 수정해야 할 것 같습니다.

**Comment by KangyeolLee** [comment]
해당 경로가 `/login` 으로 지정되어야 하는데,

현재 `/signup/agree` 로 지정되었습니다...

저도 제대로 확인을 못하고 승인을 했네요.

이슈는 다시 활성화 하겠습니다.

죄송합니다.

**Comment by TsooranKim** [comment]
아아아 죄송합니다. 아무생각없이 회원가입으로 넘겨버렸네요. 수정하겠습니다.
