### ISSUE TITLE
[document] branch 이름 짓는 방법

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/baemin-17#46]
브런치 이름 짓는 방법을 아래와 같이 정하고자 합니다.

**PREFIX/#ISSUE-ID[-KEYWORD]** 또는 **PREFIX/KEYWORD**

## PREFIX

| 타입 | prefix |
| --- | --- |
| feature | feature |
| bug | bugfix |
| refactor | refactor |
| hotfix | hotfix |

branch를 만들기 전에 가능한 반드시 issue를 작성하여 id를 생성합니다.<br />
하지만 정말 급한 버그인 경우 hotfix로 만들고 issue가 없기에 id 없이 알기 쉬운 keyword를 기입합니다.

issus id가 있지만 필요하다면 keyword를 붙여도 좋습니다.

**Comment by KangyeolLee** [comment]
네 동의합니다~

관련해서 Wiki에 등록해주시면 될 것 같습니다 :)
