### ISSUE TITLE
[document] PR 작성 및 머지 방법

### ISSUE THREAD

**Issue by TsooranKim** [woowa-techcamp-2021/baemin-17#48]
PR제목 앞에는 issue 타입과 issue id를 /를 이용해 구분하고 대괄호로 감쌉니다.<br />
대괄호 안에 branch 이름을 기입해도 괜찮습니다.
전체 변경 내용을 요약하는 제목을 작성합니다.<br />

hotfix가 아닌 이상 반드시 검토자를 지정합니다.

issue를 연결합니다.

내용에는 변경내용을 각각 요약하여 기술합니다.

검토자에게 모두 허가를 받으면 본인이 직접 머지 합니다.<br />
머지는 본 레포지토리에서는 Squash and merge를 사용합니다.

**Comment by KangyeolLee** [comment]
좋습니다~

번외로 PR은 아니지만

이슈의 경우에는 `Assignees`를 어떻게 지정하는 것이 좋을까요?

**Comment by TsooranKim** [comment]
> 이슈의 경우에는 `Assignees`를 어떻게 지정하는 것이 좋을까요?

음~ 본인이 해야하는 거면 보인으로 해놓고 해줘야 하는거면 상대방 지정하고 둘다하는거면 둘다 지정하는 식으로 하시죠 ㅎㅎ
